name: Build webapp

on: 
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  webapp: 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
          NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}
          BASE_URL=${{ secrets.API_BASE_URL }}
    - name: Deploy webapp
      uses: appleboy/ssh-action@master
      with:
        host: septotrip.com
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker-compose -f docker-compose.prod.yml pull webapp
          docker-compose -f docker-compose.prod.yml stop webapp
          docker-compose -f docker-compose.prod.yml rm -f webapp
          docker-compose -f docker-compose.prod.yml --env-file ./.env up -d webapp