name: Lint webapp

on:
  pull_request: 
    branches: [ dev, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Substitute token and install dépendencies
      run: token=${{ secrets.GITHUB_TOKEN }} && envsubst < src/environments/environment.template.ts > src/environments/environment.prod.ts && yarn install
    - name: Lint
      run: yarn lint
